from .base import ClientPacket, ServerPacket
from .server import (
    WelcomePacket,
    KeyPacket,
    TravelPacket,
    PingRequestPacket,
    PowChallengePacket,
    EvalChallengePacket,
    RoomPacket,
    PlayerListPacket,
    ServerMessagePacket,
    MockupsPacket,
    UpdatePacket,
    BroadcastPacket,
    CameraPacket,
    ChatPacket,
    KickPacket,
    DeathPacket,
    TurnstileChallengePacket,
)
from .client import (
    KeyRequestPacket,
    TrackingPacket,
    PingResponsePacket,
    SpawnRequestPacket,
    EvalAnswerPacket,
    PowAnswerPacket,
    TankUpgradePacket,
    SkillUpgradePacket,
    CommandPacket,
    TogglePacket,
    LevelUpCheatPacket,
    KeyPressPacket,
    ChatMessagePacket,
    PlayerActionPacket,
    SuicidePacket,
    AbilityPacket,
    SaveScorePacket,
    TurnstileAnswerPacket,
)

SERVER_PACKETS = {cls.TAG: cls for cls in (
    WelcomePacket, KeyPacket, TravelPacket, PingRequestPacket,
    PowChallengePacket, EvalChallengePacket, RoomPacket, PlayerListPacket,
    ServerMessagePacket, MockupsPacket, UpdatePacket, BroadcastPacket,
    CameraPacket, ChatPacket, KickPacket, DeathPacket,
    TurnstileChallengePacket,
)}

__all__ = [
    "ServerPacket", "ClientPacket", "SERVER_PACKETS",
    "WelcomePacket", "KeyPacket", "TravelPacket", "PingRequestPacket",
    "PowChallengePacket", "EvalChallengePacket", "RoomPacket",
    "PlayerListPacket", "ServerMessagePacket", "MockupsPacket",
    "UpdatePacket", "BroadcastPacket", "CameraPacket", "ChatPacket",
    "KickPacket", "DeathPacket",
    "KeyRequestPacket", "TrackingPacket", "PingResponsePacket",
    "SpawnRequestPacket", "EvalAnswerPacket", "PowAnswerPacket",
    "TankUpgradePacket", "SkillUpgradePacket", "CommandPacket",
    "TogglePacket", "LevelUpCheatPacket", "KeyPressPacket",
    "ChatMessagePacket", "PlayerActionPacket", "SuicidePacket",
    "AbilityPacket", "SaveScorePacket",
    "TurnstileChallengePacket", "TurnstileAnswerPacket",
]
